spring.profiles.active=local
<<<<<<< HEAD

spring.application.name=UfapeMarket
spring.datasource.url=jdbc:postgresql://localhost:5432/UfapeMarket

=======
spring.application.name=MarketUFAPE
spring.datasource.url=jdbc:postgresql://localhost:5432/MarketUFAPE
>>>>>>> fe574c72f238a1a5c7a1ef0e36b30dabfa57b1f8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081