spring.profiles.active=local
<<<<<<< HEAD
spring.application.name=MarketUFAPE
spring.datasource.url=jdbc:postgresql://localhost:5432/MarketUFAPE
=======
spring.application.name=UfapeMarket
spring.datasource.url=jdbc:postgresql://localhost:5432/UfapeMarket
>>>>>>> 483cf256a4f7f4941cd2563f83115384bab72444

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081